// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiwtQz7LMEAGhP6lXFRIzLGKIWGzg1CE',
    appId: '1:107522573428:web:f917cbb29c2e9a8d4a3d21',
    messagingSenderId: '107522573428',
    projectId: 'oxyboots-63072',
    authDomain: 'oxyboots-63072.firebaseapp.com',
    storageBucket: 'oxyboots-63072.appspot.com',
    measurementId: 'G-C2D7PP3WQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxK8bsRea_Z7juQ0tnQPid28WXx1IEDYg',
    appId: '1:107522573428:android:4d96394539a9816b4a3d21',
    messagingSenderId: '107522573428',
    projectId: 'oxyboots-63072',
    storageBucket: 'oxyboots-63072.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw7ICvTz5jjgbcr-pdj2kDUkiBXNft3f8',
    appId: '1:107522573428:ios:1c2fe984cf59dfd34a3d21',
    messagingSenderId: '107522573428',
    projectId: 'oxyboots-63072',
    storageBucket: 'oxyboots-63072.appspot.com',
    iosBundleId: 'com.example.oxyboots',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw7ICvTz5jjgbcr-pdj2kDUkiBXNft3f8',
    appId: '1:107522573428:ios:470e772a12004d444a3d21',
    messagingSenderId: '107522573428',
    projectId: 'oxyboots-63072',
    storageBucket: 'oxyboots-63072.appspot.com',
    iosBundleId: 'com.example.oxyboots.RunnerTests',
  );
}
